### ISSUE TITLE
null on csrf token

### ISSUE THREAD

**Issue by iniznet** [smashed-egg/laravel-route-annotation#1]
Hi,

I have encountered an issue where generating a CSRF token using `csrf_token()` results in an empty or null value,
```html
<meta name="csrf-token" content="">
```

I'm registering routes as described in the GitHub README,
```php
Route::directory(dirname(__DIR__) . '/app/Http/Controllers'); // first try
Route::annotation(App\Http\Controllers\HomeController::class); // second try
```

Controller
```php
use SmashedEgg\LaravelRouteAnnotation\Route;

class HomeController extends Controller
{
    #[Route('/', name: 'home', methods: ['GET'])]
    public function index(Request $request)
    {
        return view('home');
    }
}
```

It works fine when I'm using normal routing methods.

**Comment by tomgrohl** [comment]
Hi

Thanks for opening this packages first issue 🙌 

I think it's not working because you need to add the `web` middleware to your route, as this calls the StartSession middleware. As the csrf token needs to be stored in the session.

I'm not at a computer to check but if you could try that please and get back to me with your results. 

Thanks

**Comment by iniznet** [comment]
Thanks, it works!

Initially, I put them inside the `home` route arguments, but I changed it to this way to avoid repetition.
```php
use SmashedEgg\LaravelRouteAnnotation\Route;

#[Route(middleware: ['web'])]
class HomeController extends Controller
{
```

**Comment by tomgrohl** [comment]
Yes doing it there acts like a route group, saving repetition.

This is a bit of is a caveat. Which is something I'd like to get working is to be able to do something like this:

```php
Route::group(['middleware' => 'web'],  function() {

    Route::directory(dirname(__DIR__) . '/app/Http/Controllers');

});
```

Which I don't think currently works.

This would save more repetition.

**Comment by tomgrohl** [comment]
I'm going to leave this open just incase there is a bug here in relation to my example above, as that should technically work.

**Comment by tomgrohl** [comment]
@iniznet version 0.3.1 is now out. Route groups and scoped bindings now work as expected so you can wrap your calls like so:

```php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

Route::middleware('web')->prefix('/app')->as('app.')->scopeBindings()->group(function() {
    Route::directory(__DIR__ . '/Controllers');
    // OR
    Route::annotation(HomeController::class);
});
```

You can also define scope bindings using annotations:

```php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;
use Inertia\Inertia;
use SmashedEgg\LaravelRouteAnnotation\Route;

class PostController extends Controller
{
    #[Route(uri: '/posts/{post}/comments/{comment}', name: 'post.comments.view', scopeBindings: true)]
    public function viewComment(Post $post, Comment $comment)
    {
        return Inertia::render('Post/Comment', [
            'post' => $post,
            'comment' => $comment,
        ]);
    }
}
```
