### ISSUE TITLE
Priority in route 

### ISSUE THREAD

**Issue by charlietyn** [smashed-egg/laravel-route-annotation#2]
Hello,
Great package, would it be possible to add a priority to the route like on Sympfony :
https://symfony.com/doc/current/routing.html#priority-parameter

Thanks to you

**Comment by tomgrohl** [comment]
Hi

Thanks for opening.

That looks to be a good addition to make, so I'll work on it ASAP and it should be released as part of version 0.4.0 or 1.0.

Thanks

**Comment by tomgrohl** [comment]
Hi @charlietyn 

I've released version 4.1 which includes support for priority. Below is an example of how it can be used:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Routing\Controller;
use SmashedEgg\LaravelRouteAnnotation\Route;

#[Route('/simple', name: 'simple.')]
class SimpleController extends Controller
{
    #[Route('/{something}', name: 'something')]
    public function home()
    {
    }

    #[Route('/list', name: 'list', priority: 1)]
    public function list()
    {

    }
}
```

Priority defaults to 0, and in the above, list would have higher priority than something.

If you could test and feedback that would be great.

Thanks

Tom

**Comment by charlietyn** [comment]
Hi tom thanks for priority feature but i have another problem and is add
prefix to de uri, i see that you put only as prefix the enripoint first
name like api, there is possible add prefix field to the Route class like
original rute of laravel
thanks

**Comment by tomgrohl** [comment]
@charlietyn if you could start a discussion [here](https://github.com/smashed-egg/laravel-route-annotation/discussions), with what you are trying to achieve I can try and help.
